version: "2"
services:
  app:
    container_name: goapp
    build: .
    command: ./main
    ports:
      - "8080:8080"
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./mongo:/mongo/db
    ports:
      - "27017:27017"
